### ISSUE TITLE
vcproject refers to ../common/SerialDialog.c but it doesn't exist.

### ISSUE THREAD

**Issue by tabithabragg** [ewinemiller/dcg#2]
dcg/GroundControl.vcproject refers to ../common/SerialDialog.c but the file doesn't exist anywhere in the code repo.  This is preventing a successful build.  

From the .vcproject:
	RelativePath="..\Common\SerialDialog.c"

**Comment by ewinemiller** [comment]
Thanks. Give it another whirl please. Had uploaded the old project file instead of the new one created when I updated to VS 2017.
